{% set version = "1.13.1" %}
{% set sha256 = "9d83ba6d5dfdd0aa32d6bfc4b7cd63c38abc6a3bf22d04a4bf194113c9da8ffe" %}

package:
  name: dymos
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dymos/dymos-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy <2
    - scipy
    - openmdao >=3.27

test:
  requires:
    - aiounittest
    - numpydoc >=1.1
    - parameterized
    - pycodestyle >=2.4.0
    - pyoptsparse
    - testflo >=1.3.6
    # not fully testing viz YET, but does fulfill undocumented tornado dep
    - bokeh >=1.3.4
    - colorama
    - matplotlib-base
    - notebook
    - pydoe3
    - pyparsing
    - tabulate
    # for pip check
    - pip
    - python {{ python_min }}
  imports:
    - dymos
  commands:
    - python -m pip check

about:
  home: https://openmdao.github.io/dymos
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Dymos framework infrastructure
  description: |
    Dymos is a framework for the simulation and optimization of dynamical systems
    within the OpenMDAO Multidisciplinary Analysis and Optimization environment.
    Dymos leverages implicit and explicit simulation techniques to simulate generic
    dynamic systems of arbitary complexity.
  doc_url: https://openmdao.github.io/dymos
  dev_url: https://github.com/OpenMDAO/dymos
  doc_source_url: https://github.com/OpenMDAO/dymos/tree/master/docs

extra:
  recipe-maintainers:
    - robfalck
    - swryan
    - sanbales
