{% set version = "1.11.0" %}
{% set sha256 = "5438c65eefc756c49dbcd9186c69078a6b2f1b96bf52a9f340106cbc3058b72e" %}

package:
  name: dymos
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dymos/dymos-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - packaging
  run:
    - openmdao >=3.27
    - numpy
    - python >=3.8
    - scipy

test:
  requires:
    - aiounittest
    - numpydoc >=1.1
    - parameterized
    - pycodestyle >=2.4.0
    - pyoptsparse
    - testflo >=1.3.6
    # not fully testing viz YET, but does fulfill undocumented tornado dep
    - bokeh >=1.3.4
    - colorama
    - matplotlib-base
    - notebook
    - pydoe3
    - pyparsing
    - tabulate
    # for pip check
    - pip
  imports:
    - dymos
  commands:
    - python -m pip check

about:
  home: https://openmdao.github.io/dymos
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Dymos framework infrastructure
  description: |
    Dymos is a framework for the simulation and optimization of dynamical systems
    within the OpenMDAO Multidisciplinary Analysis and Optimization environment.
    Dymos leverages implicit and explicit simulation techniques to simulate generic
    dynamic systems of arbitary complexity.
  doc_url: https://openmdao.github.io/dymos
  dev_url: https://github.com/OpenMDAO/dymos
  doc_source_url: https://github.com/OpenMDAO/dymos/tree/master/docs

extra:
  recipe-maintainers:
    - swryan
    - sanbales
