{% set version = "1.8.0" %}
{% set sha256 = "595347a4586982f118353d1e9275f404966ab46c5220ecdecf487076766624bd" %}

package:
  name: dymos
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dymos/dymos-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    # remove <3.27 once Dymos fixes their set_val calls
    - openmdao >=3.17.0,<3.27
    - numpy
    - packaging
    - python >=3.8
    - requests
    - scipy

test:
  requires:
    - aiounittest
    - numpydoc >=0.9.1
    - parameterized
    - pycodestyle >=2.4.0
    - pyoptsparse
    - testflo >=1.3.6
    # not fully testing viz YET, but does fulfill undocumented tornado dep
    - bokeh >=1.3.4
    - colorama
    - matplotlib-base
    - notebook
    - pydoe2
    - pyparsing
    - tabulate
    # for pip check
    - pip
    # from sphinx
    - jinja2 >=2.3,<3.0
    - markupsafe <2.0
  imports:
    - dymos
  commands:
    - python -m pip check

about:
  home: https://openmdao.github.io/dymos
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Dymos framework infrastructure
  description: |
    Dymos is a framework for the simulation and optimization of dynamical systems 
    within the OpenMDAO Multidisciplinary Analysis and Optimization environment. 
    Dymos leverages implicit and explicit simulation techniques to simulate generic 
    dynamic systems of arbitary complexity.
  doc_url: https://openmdao.github.io/dymos
  dev_url: https://github.com/OpenMDAO/dymos
  doc_source_url: https://github.com/OpenMDAO/dymos/tree/master/docs

extra:
  recipe-maintainers:
    - sanbales
